### ISSUE TITLE
flame-chart-json: ValueError: invalid literal for int() with base 10: '(idle) 135\n'

### ISSUE THREAD

**Issue by eliasp** [uber/pyflame#156]
Running `flame-chart-json` on the output of `pyflame` just fails with `ValueError: invalid literal for int() with base 10: '(idle) 135\n'` here.

 - [x] Include the output of `pyflame -v`: `pyflame 1.6.6 linux-gnu x86_64 (ABI list: 26 36)`
 - [x] Include the exact version of the Python interpreter you are profiling: `Python 3.6.5`
 - [x] Include the exact text of any error messages:

```
$ flame-chart-json < pyflame.out > pyflame.cpuprofile
Traceback (most recent call last):
  File "/usr/bin/flame-chart-json", line 144, in
    fc.start()
  File "/usr/bin/flame-chart-json", line 117, in start
    ts = int(line)
ValueError: invalid literal for int() with base 10: '(idle) 135\n'
```

**Comment by eliasp** [comment]
My bad - I wasn't generating the output using `--flamegraph` - so it's quite obvious why it fails ;)
